### ISSUE TITLE
点群が表示されない

### ISSUE THREAD

**Issue by dif-engine** [YOODS/SampleSRC#1]
NEDO講座「RoVI」入門のPDFにしたがって点群を表示しようとしています．
１．~/catkin̲ws/src/rovi　にて git clone https://github.com/YOODS/SampleSRC.git しました．
２．「(1) 新規にターミナルをふたつ起動し、サンプルプログラムおよびビュー
アを起動します。
roslaunch rovi rovi̲capture.launch
roslaunch rovi viewer.launch
これで起動されるサンプルノードは10秒間隔で3D撮影を実行して、rviz
はその都度更新された点群を表示します。」
とある通りに起動してみましたがrviz の画面に何も表示されません．

**Comment by Kan-Harada** [comment]
SampleSRCのブランチをkineticとnoeticにしました。いずれも動作確認済みです。
melodicで使用する場合は、kineticを使ってください。

★roviもブランチ名をROSのバージョン名に合わせました。お手数ですが、再度cloneしてください。
